"""Central Authorization & Data Scope Management Package."""

from .access_control import (
    AuthorizationError,
    SecurityContext,
    build_security_context,
    filter_dataset,
    get_anonymous_context,
    get_my_access_profile,
    get_security_context_from_headers,
    simulate_user_access,
)
from .permissions import (
    get_all_permissions,
    get_permission_catalog,
    is_valid_permission,
    register_permission,
)
from .policies import PolicyDecision, evaluate_policy
from .roles import (
    BUILTIN_ROLES,
    get_builtin_roles,
    is_builtin_role,
    validate_role_permissions,
)
from .scopes import (
    DataScope,
    SCOPE_HIERARCHY,
    SCOPE_LABELS,
    get_available_scopes,
    is_valid_scope,
    normalize_scope,
    scope_allows_resource,
)
from .sharing import (
    VALID_RESOURCE_TYPES,
    VALID_SHARE_PERMISSIONS,
    get_shares,
    get_user_shares,
    is_shared_with,
    revoke as revoke_share,
    share as share_resource,
)
from .storage import (
    clone_role,
    create_custom_role,
    create_group,
    delete_custom_role,
    delete_group,
    get_group_by_id,
    get_role_by_id,
    get_user_group_ids,
    get_user_profile,
    init_authorization_db,
    invalidate_cache,
    list_all_groups,
    list_all_roles,
    save_user_profile,
    update_custom_role,
    update_group,
)

__all__ = [
    "AuthorizationError",
    "SecurityContext",
    "build_security_context",
    "filter_dataset",
    "get_anonymous_context",
    "get_my_access_profile",
    "get_security_context_from_headers",
    "simulate_user_access",
    "get_all_permissions",
    "get_permission_catalog",
    "is_valid_permission",
    "register_permission",
    "PolicyDecision",
    "evaluate_policy",
    "BUILTIN_ROLES",
    "get_builtin_roles",
    "is_builtin_role",
    "validate_role_permissions",
    "DataScope",
    "SCOPE_HIERARCHY",
    "SCOPE_LABELS",
    "get_available_scopes",
    "is_valid_scope",
    "normalize_scope",
    "scope_allows_resource",
    "VALID_RESOURCE_TYPES",
    "VALID_SHARE_PERMISSIONS",
    "get_shares",
    "get_user_shares",
    "is_shared_with",
    "revoke_share",
    "share_resource",
    "clone_role",
    "create_custom_role",
    "create_group",
    "delete_custom_role",
    "delete_group",
    "get_group_by_id",
    "get_role_by_id",
    "get_user_group_ids",
    "get_user_profile",
    "init_authorization_db",
    "invalidate_cache",
    "list_all_groups",
    "list_all_roles",
    "save_user_profile",
    "update_custom_role",
    "update_group",
]

