"""Canonical Event, Finding, Incident, and Forensic Models for LogScope."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class ConclusionLevel(str, Enum):
    """Forensic conclusion level representing analytical certainty."""
    OBSERVED = "observed"                                     # نشاط ملاحظ
    SUSPICIOUS = "suspicious"                                 # نشاط مشبوه
    LIKELY_MALICIOUS = "likely_malicious"                     # نشاط خبيث مرجح
    CORRELATED_SUSPICIOUS = "correlated_suspicious"           # نشاط مشبوه مترابط
    LIKELY_SUCCESSFUL = "likely_successful"                   # هجوم مرجح نجاحه
    CONFIRMED = "confirmed"                                   # اختراق / هجوم مؤكد بالأدلة

    @property
    def label_ar(self) -> str:
        labels = {
            self.OBSERVED: "نشاط ملاحظ (Observed)",
            self.SUSPICIOUS: "اشتباه أمني (Suspicious)",
            self.LIKELY_MALICIOUS: "نشاط خبيث مرجح (Likely Malicious)",
            self.CORRELATED_SUSPICIOUS: "سلسلة سلوك مشبوهة (Correlated)",
            self.LIKELY_SUCCESSFUL: "هجوم مرجح نجاحه (Likely Successful)",
            self.CONFIRMED: "تهديد أمني مؤكد (Confirmed Threat)",
        }
        return labels.get(self, str(self.value))


class ActionDisposition(str, Enum):
    """Disposition of the security event / firewall action."""
    ALLOW = "allow"
    BLOCK = "block"
    ALERT = "alert"
    UNKNOWN = "unknown"

    @classmethod
    def from_string(cls, action: str) -> ActionDisposition:
        act = str(action or "").strip().lower()
        if act in {"block", "blocked", "drop", "dropped", "deny", "denied", "quarantine", "quarantined", "reject", "discard", "حظر", "إسقاط", "منع"}:
            return cls.BLOCK
        if act in {"allow", "allowed", "permit", "permitted", "pass", "passed", "accept", "accepted", "سماح", "قبول"}:
            return cls.ALLOW
        if act in {"alert", "alerted", "warn", "warning", "audit", "logged", "تنبيه", "إنذار"}:
            return cls.ALERT
        return cls.UNKNOWN


@dataclass
class DetectionFinding:
    """A granular finding generated by a domain-specific detector."""
    detection_id: str                                         # e.g., 'DET-WIN-BRUTEFORCE-001'
    title_ar: str
    description_ar: str
    base_severity: int = 50                                  # 0 to 100
    confidence: int = 70                                     # 0 to 100
    conclusion_level: ConclusionLevel = ConclusionLevel.SUSPICIOUS
    mitre_tactics: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)
    threat_family: str = "حدث أمني (Security Event)"
    evidence: list[str] = field(default_factory=list)
    contributing_factors: list[str] = field(default_factory=list)
    mitigating_factors: list[str] = field(default_factory=list)


@dataclass
class RiskExplanation:
    """Structured, explainable justification for Risk and Confidence scores."""
    base_score: int = 0
    final_score: int = 0
    confidence_score: int = 50
    reasons_for_increase: list[str] = field(default_factory=list)
    reasons_for_decrease: list[str] = field(default_factory=list)
    matched_rules: list[str] = field(default_factory=list)
    contributing_events_count: int = 1
    confidence_factors: list[str] = field(default_factory=list)

    def to_dict(self) -> dict[str, Any]:
        return {
            "base_score": self.base_score,
            "final_score": self.final_score,
            "confidence_score": self.confidence_score,
            "reasons_for_increase": self.reasons_for_increase,
            "reasons_for_decrease": self.reasons_for_decrease,
            "matched_rules": self.matched_rules,
            "contributing_events_count": self.contributing_events_count,
            "confidence_factors": self.confidence_factors,
        }


@dataclass
class Incident:
    """A multi-event correlated security incident."""
    incident_id: str                                         # e.g., 'INC-2026-000123'
    title_ar: str
    description_ar: str
    start_time: str = ""
    end_time: str = ""
    source_ips: list[str] = field(default_factory=list)
    target_ips: list[str] = field(default_factory=list)
    usernames: list[str] = field(default_factory=list)
    devices: list[str] = field(default_factory=list)
    event_count: int = 0
    detection_ids: list[str] = field(default_factory=list)
    mitre_tactics: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)
    risk_score: int = 75
    confidence_score: int = 80
    conclusion_level: ConclusionLevel = ConclusionLevel.CORRELATED_SUSPICIOUS
    timeline_events: list[dict[str, Any]] = field(default_factory=list)

    def get_recommendations(self) -> list[str]:
        recs = []
        det_str = " ".join(self.detection_ids)
        tech_str = " ".join(self.mitre_techniques)
        events_str = str(self.timeline_events)

        if "T1110" in tech_str or "BRUTEFORCE" in det_str or "TAKEOVER" in det_str:
            recs.append("إعادة تعيين كلمة المرور فوراً وتفعيل المصادقة متعددة العوامل (MFA) للحسابات المستهدفة.")
            recs.append("حظر عناوين IP المهاجمة في جدار الحماية الخارجي وWAF.")
        if "T1078" in tech_str or "PRIV" in det_str or "4672" in events_str:
            recs.append("مراجعة صلاحيات الحساب وعزل الجلسة النشطة فورياً والتحقق من التغييرات في Active Directory.")
            recs.append("فحص السجلات الإدارية للتأكد من عدم إنشاء حسابات ظل أو أبواب خلفية (Persistence).")
        if "7045" in events_str or "4688" in events_str or "MALWARE" in det_str:
            recs.append("عزل المحطة الطرفية أو الخادم المصاب عن الشبكة فوراً وإجراء مسح شامل ببرمجيات EDR.")
            recs.append("مراجعة العمليات المنفذة والخدمات المثبتة حديثاً واستخراج البصمات التخريبية.")
        if not recs:
            recs.append("التحقق من صحة النشاط وسؤال المستخدم المعني عن مصدر وتوقيت المحاولة.")
            recs.append("متابعة مراقبة سجلات النظام وسجلات جدران الحماية للبحث عن أي محاولات إضافية.")
        return recs

    def to_dict(self) -> dict[str, Any]:
        return {
            "incident_id": self.incident_id,
            "title_ar": self.title_ar,
            "description_ar": self.description_ar,
            "start_time": self.start_time,
            "end_time": self.end_time,
            "source_ips": self.source_ips,
            "target_ips": self.target_ips,
            "usernames": self.usernames,
            "devices": self.devices,
            "event_count": self.event_count,
            "detection_ids": self.detection_ids,
            "mitre_tactics": self.mitre_tactics,
            "mitre_techniques": self.mitre_techniques,
            "risk_score": self.risk_score,
            "confidence_score": self.confidence_score,
            "conclusion_level": str(self.conclusion_level.value if hasattr(self.conclusion_level, "value") else self.conclusion_level),
            "severity": "حرج" if self.risk_score >= 85 else ("مرتفع" if self.risk_score >= 70 else ("متوسط" if self.risk_score >= 40 else "منخفض")),
            "timeline_events": self.timeline_events,
            "recommendations": self.get_recommendations(),
        }


@dataclass
class CanonicalEvent:
    """Unified internal representation of an event across all heterogeneous log sources."""
    # Timestamps
    event_time: str = ""
    timestamp_dt: datetime | None = None

    # Network Entities
    source_ip: str = ""
    destination_ip: str = ""
    source_port: int | None = None
    destination_port: int | None = None
    protocol: str = ""
    service_name: str = ""

    # Identities & Endpoints
    username: str = ""
    hostname: str = ""
    device: str = ""

    # Event Attributes
    event_id: str = ""
    action: str = ""
    action_disposition: ActionDisposition = ActionDisposition.UNKNOWN
    status: str = ""
    priority: str = "Info"
    message: str = ""

    # Source & Taxonomy
    log_source: str = "generic"
    product: str = ""
    category: str = ""
    report_family: str = "custom"

    # Context & Raw Evidence (Never Discarded!)
    raw_fields: dict[str, Any] = field(default_factory=dict)
    extracted_ips: set[str] = field(default_factory=set)

    # Forensic & Detection Results
    findings: list[DetectionFinding] = field(default_factory=list)
    risk_score: int = 0
    confidence_score: int = 50
    severity: str = "منخفض"
    conclusion_level: ConclusionLevel = ConclusionLevel.OBSERVED
    description_ar: str = ""
    action_ar: str = ""
    threat_family: str = "حدث أمني (Security Event)"
    incident_id: str | None = None
    detection_ids: list[str] = field(default_factory=list)
    mitre_tactics: list[str] = field(default_factory=list)
    mitre_techniques: list[str] = field(default_factory=list)
    risk_explanation: RiskExplanation | None = None

    # Backward Compatibility Aliases
    @property
    def user_account(self) -> str:
        return self.username

    @user_account.setter
    def user_account(self, val: str) -> None:
        self.username = str(val or "")

    @property
    def src_ip(self) -> str:
        return self.source_ip

    @src_ip.setter
    def src_ip(self, val: str) -> None:
        self.source_ip = str(val or "")

    @property
    def destination(self) -> str:
        return self.destination_ip

    @destination.setter
    def destination(self, val: str) -> None:
        self.destination_ip = str(val or "")

    @property
    def description(self) -> str:
        return self.message

    @description.setter
    def description(self, val: str) -> None:
        self.message = str(val or "")

    @property
    def event_source(self) -> str:
        return self.log_source

    @event_source.setter
    def event_source(self, val: str) -> None:
        self.log_source = str(val or "")

    @property
    def record_count(self) -> int:
        return 1

    def to_dict(self) -> dict[str, Any]:
        """Project into the canonical dictionary format expected by UI, SQLite, and Reports."""
        act_display = self.action_ar or self.action.upper() or "غير محدد"
        desc_display = self.description_ar or self.message or "حدث أمني صادر من النظام"

        return {
            "event_time": self.event_time,
            "event_id": self.event_id,
            "priority": self.priority,
            "event_source": self.log_source,
            "device": self.device or self.hostname,
            "user_account": self.username,
            "src_ip": self.source_ip,
            "destination": self.destination_ip,
            "protocol": self.protocol,
            "src_port": str(self.source_port) if self.source_port is not None else "",
            "dst_port": str(self.destination_port) if self.destination_port is not None else "",
            "service_name": self.service_name,
            "description": self.message,
            "description_ar": desc_display,
            "action": self.action,
            "action_ar": act_display,
            "threat_family": self.threat_family,
            "report_family": self.report_family,
            "record_count": 1,
            "raw_fields": self.raw_fields,
            "risk_score": self.risk_score,
            "base_risk_score": self.risk_score,
            "confidence_score": self.confidence_score,
            "severity": self.severity,
            "conclusion_level": self.conclusion_level.value,
            "incident_id": self.incident_id,
            "detection_ids": self.detection_ids,
            "mitre_tactics": self.mitre_tactics,
            "mitre_techniques": self.mitre_techniques,
            "extracted_ips": sorted(list(self.extracted_ips)),
        }
